#ifndef _ROCKCHIP_CONFIG_H
#define _ROCKCHIP_CONFIG_H

#define SENSOR_WIDTH  1080
#define SENSOR_HEIGHT 720

#define MPP_OUT_WIDTH SENSOR_WIDTH
#define MPP_OUT_HEIGHT SENSOR_HEIGHT

#define MPP_FMT MPP_FMT_YUV420SP
#define V4L2_FMT V4L2_PIX_FMT_NV12
#define MPP_ENCODE_TYPE MPP_VIDEO_CodingHEVC

#endif